"""Backward-compatible aliases for previous `new_*` route names."""

from django.urls import path
from django.views.generic import RedirectView

from games.section_urls import section_root_urlpatterns
from games.views import ui

urlpatterns = [
    path('', ui.hub, name='new_hub'),
    path('play-mode/', ui.set_play_mode, name='new_set_play_mode'),
    path('migrate-anon-attempts/', ui.migrate_anon_attempts, name='new_migrate_anon_attempts'),
    path('anon-migrate-count/', ui.anon_migrate_count, name='new_anon_migrate_count'),
    path('answer/<int:task_id>/', ui.get_answer, name='new_get_answer'),
    path('answer/<int:task_id>/<int:line_index>/', ui.get_replacements_line_answer, name='new_get_replacements_line_answer'),
    path('answer/<int:task_id>/word/<int:word_index>/', ui.get_raddle_word_answer, name='new_get_raddle_word_answer'),
    path('like-dislike/<int:task_id>/', ui.like_dislike, name='new_like_dislike'),
    path('bug-report/<int:task_id>/', ui.bug_report, name='new_bug_report'),
    path('ladder/today/', ui.ladder_today_page, name='new_ladder_today'),
    path('ladder/last/', ui.ladder_last_page, name='new_ladder_last'),
    path('ladder/progress/', ui.game_task_group_progress, {'game_id': 'ladder'}, name='new_ladder_progress'),
    path('ladder/', ui.ladder_hub_page, name='new_ladder_hub'),
    # Must precede ladder/<str>/ so "results" is not treated as a task-group number.
    path('ladder/results/', ui.section_results_page, {'game_id': 'ladder'}),
    path('ladder/<str:task_group_number>/results/', ui.ladder_word_results_page, name='new_ladder_word_results'),
    path('ladder/<str:task_group_number>/', ui.task_group_page, {'game_id': 'ladder'}, name='new_ladder_task_group'),
    path('create_ladder/', ui.offer_ladder_page, name='new_create_ladder'),
    path('create_ladder/create/', ui.offer_ladder_create, name='new_create_ladder_create'),
    path('create_ladder/<int:offer_id>/', ui.offer_ladder_detail, name='new_create_ladder_detail'),
    path('create_ladder/<int:offer_id>/send/', ui.offer_ladder_send, name='new_create_ladder_send'),
    path('create_ladder/<int:offer_id>/reset/', ui.offer_ladder_reset, name='new_create_ladder_reset'),
    path('offer_ladder/', RedirectView.as_view(pattern_name='new_create_ladder', permanent=False, query_string=True)),
    path('offer_ladder/create/', RedirectView.as_view(pattern_name='new_create_ladder_create', permanent=False, query_string=True)),
    path('offer_ladder/<int:offer_id>/', RedirectView.as_view(pattern_name='new_create_ladder_detail', permanent=False, query_string=True)),
    path('offer_ladder/<int:offer_id>/send/', RedirectView.as_view(pattern_name='new_create_ladder_send', permanent=False, query_string=True)),
    path('offer_ladder/<int:offer_id>/reset/', RedirectView.as_view(pattern_name='new_create_ladder_reset', permanent=False, query_string=True)),
    path('alphabetty/today/', ui.alphabetty_today_page, name='new_alphabetty_today'),
    path('alphabetty/last/', ui.alphabetty_last_page, name='new_alphabetty_last'),
    path('alphabetty/progress/', ui.game_task_group_progress, {'game_id': 'alphabetty'}, name='new_alphabetty_progress'),
    path('alphabetty/', ui.alphabetty_hub_page, name='new_alphabetty_hub'),
    path('create_alphabetty/', ui.alphabetty_create_page, name='new_create_alphabetty'),
    path('create_alphabetty/create/', ui.alphabetty_create_submit, name='new_create_alphabetty_create'),
    path('offer_alphabetty/', RedirectView.as_view(pattern_name='new_create_alphabetty', permanent=False, query_string=True)),
    path('offer_alphabetty/create/', RedirectView.as_view(pattern_name='new_create_alphabetty_create', permanent=False, query_string=True)),
    path('alphabetty/<str:number>/guess/', ui.alphabetty_guess, name='new_alphabetty_guess'),
    path('alphabetty/<str:number>/state/', ui.alphabetty_state, name='new_alphabetty_state'),
    path('alphabetty/<str:number>/prefix/', ui.alphabetty_prefix, name='new_alphabetty_prefix'),
    path('alphabetty/<str:number>/suggest/', ui.alphabetty_suggest, name='new_alphabetty_suggest'),
    path('alphabetty/<str:number>/', ui.alphabetty_play_page, name='new_alphabetty_play'),
    path('games/ladder/today/', RedirectView.as_view(url='/ladder/today/', permanent=True, query_string=True)),
    path('games/ladder/last/', RedirectView.as_view(url='/ladder/last/', permanent=True, query_string=True)),
    path('games/ladder/', RedirectView.as_view(url='/ladder/', permanent=True, query_string=True)),
    path('games/ladder/<path:rest>', RedirectView.as_view(url='/ladder/%(rest)s', permanent=True, query_string=True)),
    path('games/alphabetty/today/', RedirectView.as_view(url='/alphabetty/today/', permanent=True, query_string=True)),
    path('games/alphabetty/', RedirectView.as_view(url='/alphabetty/', permanent=True, query_string=True)),
    path('games/alphabetty/<path:rest>', RedirectView.as_view(url='/alphabetty/%(rest)s', permanent=True, query_string=True)),
] + section_root_urlpatterns(
    section_game_url_name='new_section_game',
    section_results_url_name='new_section_results',
    task_group_url_name='new_task_group',
) + [
    path('games/<str:game_id>/progress/', ui.game_task_group_progress, name='new_game_progress'),
    path('games/<str:game_id>/', ui.main_game_page, name='new_main_game'),
    path('games/<str:game_id>/results/', ui.results_page, name='new_results'),
    path('games/<str:game_id>/tournament-results/', ui.tournament_results_page, name='new_tournament_results'),
    path('games/<str:game_id>/<str:task_group_number>/', ui.task_group_page, name='new_task_group'),
    path('team/name-check/', ui.team_name_check, name='new_team_name_check'),
    path('team/info/', ui.team_info, name='new_team_info'),
    path('team/create/', ui.team_create, name='new_team_create'),
    path('team/request-join/', ui.team_request_join, name='new_team_request_join'),
    path('team/join-by-password/', ui.team_join_by_password, name='new_team_join_by_password'),
    path('team/password/', ui.team_password, name='new_team_password'),
    path('team/rename/', ui.team_rename, name='new_team_rename'),
    path('team/set-primary/', ui.team_set_primary, name='new_team_set_primary'),
    path('team/join/', ui.team_join_page, name='new_team_join_page'),
    path('profile/', ui.profile, name='new_profile'),
    path('team/', ui.team, name='new_team'),
    path('pay/', ui.pay_page, name='new_pay'),
    path('pay/create-ticket-payment/', ui.create_ticket_payment, name='new_create_ticket_payment'),
    path('pay/create-crypto-ticket-payment/', ui.create_crypto_ticket_payment, name='new_create_crypto_ticket_payment'),
    path('pay/create-tribute-ticket-payment/', ui.create_tribute_ticket_payment, name='new_create_tribute_ticket_payment'),
    path('pay/ticket-status/<int:ticket_request_id>/', ui.ticket_payment_status, name='new_ticket_payment_status'),
    path('<slug>/', ui.folder, name='new_folder'),
]
