from django.contrib.auth.views import LogoutView
from django.urls import path

from games.support import actions
from games.support import views

app_name = 'support'

urlpatterns = [
    path('login/', views.SupportLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='support:login'), name='logout'),
    path('', views.hub, name='hub'),
    path('games/', views.games_browse, name='games'),
    path('sections/', views.sections_dashboard, name='sections'),
    path('ladders/', views.ladders_dashboard, name='ladders'),
    path('ladders/reorder/', views.ladders_reorder, name='ladders_reorder'),
    path('ladders/create/', views.ladders_create, name='ladders_create'),
    path('ladders/publish-start/', views.ladders_set_publish_start, name='ladders_publish_start'),
    path('ladders/offers/', views.ladder_offers_list_json, name='ladder_offers'),
    path('ladders/offers/<int:offer_id>/', views.ladder_offer_detail_json, name='ladder_offer_detail'),
    path('ladders/offers/<int:offer_id>/save/', views.ladder_offer_save, name='ladder_offer_save'),
    path('ladders/offers/<int:offer_id>/accept/', views.ladder_offer_accept, name='ladder_offer_accept'),
    path(
        'ladders/offers/<int:offer_id>/request-revision/',
        views.ladder_offer_request_revision,
        name='ladder_offer_request_revision',
    ),
    path(
        'ladders/offers/<int:offer_id>/reset-progress/',
        views.ladder_offer_reset_progress,
        name='ladder_offer_reset_progress',
    ),
    path(
        'ladders/<int:link_id>/request-revision/',
        views.ladder_link_request_revision,
        name='ladder_link_request_revision',
    ),
    path(
        'ladders/<int:link_id>/reset-progress/',
        views.ladders_reset_progress,
        name='ladders_reset_progress',
    ),
    path('ladders/<int:link_id>/', views.ladders_detail_json, name='ladders_detail'),
    path('ladders/<int:link_id>/save/', views.ladders_update, name='ladders_update'),
    path('ladders/<int:link_id>/delete/', views.ladders_delete, name='ladders_delete'),
    path('alphabetty/', views.alphabetty_dashboard, name='alphabetty'),
    path('alphabetty/reorder/', views.alphabetty_reorder, name='alphabetty_reorder'),
    path('alphabetty/create/', views.alphabetty_create, name='alphabetty_create'),
    path('alphabetty/publish-start/', views.alphabetty_set_publish_start, name='alphabetty_publish_start'),
    path('alphabetty/generate/', views.alphabetty_generate, name='alphabetty_generate'),
    path('alphabetty/<int:link_id>/', views.alphabetty_detail_json, name='alphabetty_detail'),
    path('alphabetty/<int:link_id>/save/', views.alphabetty_update, name='alphabetty_update'),
    path('alphabetty/<int:link_id>/delete/', views.alphabetty_delete, name='alphabetty_delete'),
    path('alphabetty/<int:link_id>/forbid/', views.alphabetty_forbid, name='alphabetty_forbid'),
    path('alphabetty/unban/', views.alphabetty_unban, name='alphabetty_unban'),
    path('week-tasks/', views.week_tasks_dashboard, name='week_tasks'),
    path('week-tasks/reorder/', views.week_tasks_reorder, name='week_tasks_reorder'),
    path('week-tasks/create/', views.week_tasks_create, name='week_tasks_create'),
    path('week-tasks/publish-start/', views.week_tasks_set_publish_start, name='week_tasks_publish_start'),
    path('week-tasks/generate/', views.week_tasks_generate, name='week_tasks_generate'),
    path('week-tasks/pool/', views.week_tasks_pool_catalog, name='week_tasks_pool'),
    path('week-tasks/<int:link_id>/', views.week_tasks_detail_json, name='week_tasks_detail'),
    path('week-tasks/<int:link_id>/save/', views.week_tasks_update, name='week_tasks_update'),
    path('week-tasks/<int:link_id>/delete/', views.week_tasks_delete, name='week_tasks_delete'),
    path('week-tasks/<int:link_id>/forbid/', views.week_tasks_forbid, name='week_tasks_forbid'),
    path('week-tasks/unban/', views.week_tasks_unban, name='week_tasks_unban'),
    path('social/', views.social_dashboard, name='social'),
    path('social/create/', views.social_create, name='social_create'),
    path('social/<int:post_id>/', views.social_update, name='social_update'),
    path('social/<int:post_id>/publish/', views.social_publish, name='social_publish'),
    path('social/<int:post_id>/sync-telegram/', views.social_sync_telegram, name='social_sync_telegram'),
    path('social/<int:post_id>/delete/', views.social_delete, name='social_delete'),
    path('stats/', views.stats_dashboard, name='stats'),
    path('pending/', views.pending_queue, name='pending'),
    path('live/', views.live_dashboard, name='live'),
    path('live/feed.json', views.live_feed_json, name='live_feed_json'),
    path('chain/attempt/<int:attempt_id>/', views.chain_attempt, name='chain'),
    path('action/', actions.perform_action, name='action'),
    path('actor/team/<str:team_name>/', views.actor_team, name='actor_team'),
    path('actor/user/<int:user_id>/', views.actor_user, name='actor_user'),
    path('actor/anon/<str:anon_key>/', views.actor_anon, name='actor_anon'),
    path('game/<str:game_id>/', views.game_dashboard, name='game'),
    path('preview/games/<str:game_id>/', views.preview_game, name='preview_game'),
    path(
        'preview/games/<str:game_id>/<str:task_group_number>/',
        views.preview_task_group,
        name='preview_task_group',
    ),
]
