"""
Django settings for interoves_django project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import requests
import sys


def _env_flag(name: str) -> bool:
    """True if env var is a common affirmative value (handles EB / console quirks)."""
    v = (os.getenv(name) or "").strip().lower()
    return v in ("1", "true", "yes", "on")


IS_PROD = _env_flag("IS_PROD")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_secret(secret_filename: str, *, env_var: str | None = None, default: str | None = None) -> str:
    """
    Load a secret from either an environment variable (preferred on Elastic Beanstalk)
    or from a file under BASE_DIR/secrets (useful for local dev).
    """
    if env_var:
        value = os.getenv(env_var)
        if value is not None and value != "":
            return value.strip()

    path = os.path.join(BASE_DIR, "secrets", secret_filename)
    try:
        with open(path) as f:
            return f.read().strip()
    except FileNotFoundError:
        if default is not None:
            return default
        raise


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

SECRET_KEY = load_secret("django_secret_key.txt", env_var="DJANGO_SECRET_KEY")

# Production: DEBUG only when explicitly enabled. Dev: DEBUG on unless DEBUG_ON is "false".
if IS_PROD:
    DEBUG = _env_flag("DEBUG_ON")
else:
    DEBUG = not _env_flag("DEBUG_OFF")

ALLOWED_HOSTS = [
    'interoves-django-env.eba-nbcqahns.eu-central-1.elasticbeanstalk.com',
    'interoves-django.eba-nbcqahns.eu-central-1.elasticbeanstalk.com',
    'interoves.eu-central-1.elasticbeanstalk.com',
    'interoves-prod.eu-central-1.elasticbeanstalk.com',
    'interoves-django-env.eu-central-1.elasticbeanstalk.com',
    'interoves-dev.eu-central-1.elasticbeanstalk.com',
    'interoves-env.eu-central-1.elasticbeanstalk.com',
    'ec2-35-158-115-233.eu-central-1.compute.amazonaws.com',
    '172.31.43.189',
    'interoves.com',
    'www.interoves.com',
    '127.0.0.1',
    'fat-owl-8.loca.lt',
    '3.122.72.107',
    '3.123.113.139',
    '35.158.81.206',
]

CSRF_TRUSTED_ORIGINS = [
    'https://interoves.com',
    'https://www.interoves.com',
]

def get_ec2_instance_ip():
    """
    Try to obtain the IP address of the current EC2 instance in AWS
    """
    try:
        ip = requests.get(
          'http://169.254.169.254/latest/meta-data/local-ipv4',
          timeout=0.01
        ).text
    except:
        return None
    return ip

AWS_LOCAL_IP = get_ec2_instance_ip()
ALLOWED_HOSTS.append(AWS_LOCAL_IP)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'games',
    # 'djcelery',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.vk',
    'allauth.socialaccount.providers.google',
    # 'games.telegram',

    # 'django_telegram_login',

    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',

    'storages',

    'corsheaders',

    # 'yet_another_django_profiler',

    'inlineedit',

    'explorer',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'yet_another_django_profiler.middleware.ProfilerMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'interoves_django.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, "static", "templates")
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            TEMPLATE_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'games.context_processors.ui_section_games',
            ],
        },
    },
]

WSGI_APPLICATION = 'interoves_django.wsgi.application'
ASGI_APPLICATION = 'interoves_django.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        # this can only be used in single-replica deployments
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

if 'REDIS_HOST' in os.environ:
    redis_host = os.environ['REDIS_HOST']

    try:
        redis_port = int(os.environ['REDIS_PORT'])
    except(KeyError, ValueError):
        redis_port = 6379

    redis_password = os.environ.get('REDIS_PASSWORD', '')
    redis_use_tls = os.environ.get('REDIS_TLS', '').lower() in ('1', 'true', 'yes')

    # channels_redis: hosts as (host, port), redis:// URI, or dict (redis-py connection).
    # ElastiCache transit encryption: set REDIS_TLS=1 → rediss:// (see channels_redis README).
    from urllib.parse import quote

    if redis_use_tls:
        pw = quote(redis_password, safe='') if redis_password else ''
        auth = f':{pw}@' if pw else ''
        _host_entry = {'address': f'rediss://{auth}{redis_host}:{redis_port}'}
        if os.environ.get('REDIS_SSL_CERT_REQS', '').strip().lower() == 'none':
            _host_entry['ssl_cert_reqs'] = None
        redis_hosts = [_host_entry]
    elif redis_password:
        pw = quote(redis_password, safe='')
        redis_hosts = [f'redis://:{pw}@{redis_host}:{redis_port}']
    else:
        redis_hosts = [(redis_host, redis_port)]

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": redis_hosts,
            },
        },
    }

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

if 'RDS_HOSTNAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",\
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",\
    },
}

USE_S3 = _env_flag("USE_S3")

if USE_S3:
    # Prefer IAM role credentials on Elastic Beanstalk.
    # If explicit keys are provided (env or local secrets files), boto3 will use them.
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID") or None
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY") or None

    try:
        AWS_STORAGE_BUCKET_NAME = load_secret(
            "aws_s3_storage_bucket_name.txt",
            env_var="AWS_STORAGE_BUCKET_NAME",
        )
    except FileNotFoundError:
        # Without a bucket name we can't construct media/static URLs.
        USE_S3 = False

if USE_S3:
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    # s3 static settings
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    STORAGES['staticfiles']['BACKEND'] = 'games.storage_backends.StaticStorage'
    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = 'media'
    # Media files are stored in S3 but served via /media/... through Nginx reverse-proxy.
    MEDIA_URL = '/media/'
    STORAGES['default']['BACKEND'] = 'games.storage_backends.ProxyMediaStorage'
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Authentication

AUTHENTICATION_BACKENDS = (
 'django.contrib.auth.backends.ModelBackend',
 'allauth.account.auth_backends.AuthenticationBackend',
 )

if IS_PROD:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
else:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'

if IS_PROD:
    SITE_ID = 2
else:
    SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_LOGIN_ON_GET = True

# allauth account settings to enable seamless social auto-signup
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_PROVIDERS = {
    'vk': {
        'SCOPE': [
            'profile',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'display': 'popup',
        }
    },
    # 'interoves-telegram': {
    #     'TOKEN': load_secret('telegram_token.txt'),
    #     'domain': 'https://fat-owl-8.loca.lt/',
    #     'size': 'small',
    #     'request_access': 'write'
    # },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# TELEGRAM_BOT_NAME = 'interoves_bot'
# TELEGRAM_BOT_TOKEN = load_secret('telegram_token.txt')
# TELEGRAM_LOGIN_REDIRECT_URL = 'fat-owl-8.loca.lt'

ACCOUNT_ADAPTER = 'games.users.allauth.AccountAdapter'
SOCIALACCOUNT_ADAPTER = "games.users.allauth.SocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
)

# CORS Policy

CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOW_HEADERS = (
   'Access-Control-Allow-Headers',
   'Access-Control-Allow-Credentials',
)

CORS_ORIGIN_WHITELIST = [
    'https://interoves-django-static.s3.amazonaws.com',
]

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'stderr': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
        }
    },
    'loggers': {
        'application': {
            'handlers': ['stderr'],
            'level': 'INFO',
        },
        'daphne': {
            'handlers': ['stderr'],
            'level': 'INFO',
        }
    }
}

# Inline Editor
INLINEEDIT_ADAPTORS = {
    "person-adaptor": "games.adaptors.PersonAdaptor",
}

# SQL-Explorer
EXPLORER_CONNECTIONS = { 'Default': 'default' }
EXPLORER_DEFAULT_CONNECTION = 'default'

# Celery
BROKER_URL = 'amqp://'
CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000
