# Generated by Django 2.1.5 on 2020-07-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='checker_type',
        ),
    ]
