# Generated by Django 2.1.5 on 2020-07-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_checker_checker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='checker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkers', to='games.CheckerType'),
        ),
        migrations.AlterField(
            model_name='checker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
