# Generated by Django 2.1.5 on 2020-07-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200709_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_on', to='games.Team'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_requested', to='games.Team'),
        ),
    ]
