# Generated by Django 2.1.5 on 2020-07-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='rules',
        ),
    ]
