# Generated by Django 2.1.5 on 2020-07-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200714_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='points',
        ),
    ]
