# Generated by Django 2.1.5 on 2020-07-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200714_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to='games.Checker'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='points',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
