# Generated by Django 2.1.5 on 2020-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200714_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpage',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
