# Generated by Django 2.1.5 on 2020-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200711_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='answers_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='standings_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
