# Generated by Django 2.1.5 on 2020-07-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200714_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_group',
        ),
    ]
