# Generated by Django 2.1.5 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200711_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='game',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='id',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
