# Generated by Django 2.1.5 on 2020-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_task_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='max_attempts',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True),
        ),
    ]
