# Generated by Django 2.1.5 on 2020-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200712_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
