# Generated by Django 2.1.5 on 2020-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_task_checker_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checker_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
