# Generated by Django 2.1.5 on 2020-07-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200713_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to='games.Game'),
        ),
    ]
