# Generated by Django 2.1.5 on 2020-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200714_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
