# Generated by Django 2.1.5 on 2020-07-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200714_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='result',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='value',
            new_name='text',
        ),
        migrations.AddField(
            model_name='attempt',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attemptsinfo',
            name='best_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Attempt'),
        ),
        migrations.AddField(
            model_name='attemptsinfo',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_infos', to='games.Task'),
        ),
        migrations.AddField(
            model_name='attemptsinfo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_infos', to='games.Team'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempts_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='games.AttemptsInfo'),
        ),
    ]
