# Generated by Django 2.1.5 on 2020-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200720_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
