# Generated by Django 2.1.5 on 2020-07-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200720_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAttempt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('games.attempt',),
        ),
    ]
