# Generated by Django 2.1.5 on 2020-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_proxyattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='view',
            field=models.CharField(choices=[('default', 'default'), ('table-3-n', 'table-3-n')], default='default', max_length=100),
        ),
    ]
