# Generated by Django 2.1.5 on 2020-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_taskgroup_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='image_width',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
