# Generated by Django 2.1.5 on 2020-07-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200720_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_testing',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='is_tester',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='view',
            field=models.CharField(choices=[('default', 'default')], default='default', max_length=100),
        ),
    ]
