# Generated by Django 2.1.5 on 2020-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_game_is_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='attempts_info',
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempts_infos',
            field=models.ManyToManyField(blank=True, null=True, related_name='attempts', to='games.AttemptsInfo'),
        ),
        migrations.AddField(
            model_name='attemptsinfo',
            name='mode',
            field=models.CharField(choices=[('general', 'general'), ('tournament', 'tournament')], default='general', max_length=100),
        ),
    ]
