# Generated by Django 2.1.5 on 2020-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20200721_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='possible_status',
            field=models.CharField(blank=True, choices=[('Ok', 'Ok'), ('Pending', 'Pending'), ('Wrong', 'Wrong')], max_length=100, null=True),
        ),
    ]
