# Generated by Django 2.1.5 on 2020-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_attempt_possible_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='answer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
