# Generated by Django 2.1.5 on 2020-07-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20200722_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='general_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_general', to='games.HTMLPage'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_tournament', to='games.HTMLPage'),
        ),
    ]
