# Generated by Django 2.1.5 on 2020-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20200722_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
