# Generated by Django 2.1.5 on 2020-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_team_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
