# Generated by Django 2.1.5 on 2020-07-28 17:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20200726_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptsinfo',
            name='best_attempt',
        ),
        migrations.RemoveField(
            model_name='attemptsinfo',
            name='task',
        ),
        migrations.RemoveField(
            model_name='attemptsinfo',
            name='team',
        ),
        migrations.AlterModelManagers(
            name='attempt',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='attempts_infos',
        ),
        migrations.DeleteModel(
            name='AttemptsInfo',
        ),
    ]
