# Generated by Django 2.1.5 on 2020-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
