# Generated by Django 2.1.5 on 2020-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_attempt_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
