# Generated by Django 2.1.5 on 2020-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_hint_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
