# Generated by Django 2.2.13 on 2020-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_attempt_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='author_extra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('default', 'default'), ('wall', 'wall'), ('text_with_forms', 'text_with_forms')], default='default', max_length=100),
        ),
    ]
