# Generated by Django 2.2.13 on 2020-09-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_auto_20200830_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HintAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hint_attempts', to='games.Hint')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hint_attempts', to='games.Team')),
            ],
        ),
    ]
