# Generated by Django 2.2.13 on 2020-09-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_auto_20200910_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintattempt',
            name='is_real_request',
            field=models.BooleanField(default=False),
        ),
    ]
