# Generated by Django 2.2.13 on 2020-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_hintattempt_is_real_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
