# Generated by Django 2.2.13 on 2020-10-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='general_rules',
            field=models.ForeignKey(blank=True, default='Правила тренировочного режима', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_general', to='games.HTMLPage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_playable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_tournament',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.ForeignKey(blank=True, default='Правила Десяточки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.HTMLPage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament_rules',
            field=models.ForeignKey(blank=True, default='Правила турнирного режима', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_tournament', to='games.HTMLPage'),
        ),
    ]
