# Generated by Django 2.2.13 on 2020-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_auto_20201001_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
