# Generated by Django 2.2.13 on 2020-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_project_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
