# Generated by Django 2.2.13 on 2020-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_project_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
    ]
