# Generated by Django 2.2.13 on 2020-10-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
