# Generated by Django 2.2.13 on 2020-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0052_auto_20201028_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='field_text_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
