# Generated by Django 2.2.13 on 2020-12-03 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0053_task_field_text_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ProxyAttempt',
        ),
        migrations.CreateModel(
            name='PendingAttempt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.attempt',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='is_registrable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ticket_price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='team',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_requests', to='games.Team'),
        ),
        migrations.AddField(
            model_name='registration',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='games.Game'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='games.Team'),
        ),
        migrations.CreateModel(
            name='PendingTicketRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.ticketrequest',),
        ),
    ]
