# Generated by Django 2.2.13 on 2020-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0055_auto_20201203_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='required_hints',
            field=models.ManyToManyField(to='games.Hint'),
        ),
    ]
