# Generated by Django 2.2.13 on 2020-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0056_hint_required_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='required_hints',
            field=models.ManyToManyField(blank=True, null=True, to='games.Hint'),
        ),
    ]
