# Generated by Django 2.2.13 on 2020-12-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_auto_20201219_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='required_hints',
            field=models.ManyToManyField(blank=True, to='games.Hint'),
        ),
    ]
