# Generated by Django 2.2.13 on 2021-02-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0058_auto_20201219_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
