# Generated by Django 3.1.6 on 2021-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visible_name',
            field=models.TextField(default=''),
        ),
    ]
