# Generated by Django 3.1.6 on 2021-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0060_team_visible_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='visible_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
