# Generated by Django 3.1.6 on 2021-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0061_auto_20210306_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='requires_ticket',
            field=models.BooleanField(default=True),
        ),
    ]
