# Generated by Django 3.1.6 on 2021-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0063_auto_20210327_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
