# Generated by Django 3.1.6 on 2021-04-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_auto_20210327_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_note', to='games.htmlpage'),
        ),
    ]
