# Generated by Django 3.1.6 on 2021-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_taskgroup_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='yookassa_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
