# Generated by Django 3.1.6 on 2022-02-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_ticketrequest_yookassa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ticket_price',
            field=models.IntegerField(default=750),
        ),
    ]
