# Generated by Django 3.1.6 on 2022-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0070_auto_20220626_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('default', 'default'), ('wall', 'wall'), ('text_with_forms', 'text_with_forms'), ('distribute_to_teams', 'distribute_to_teams'), ('with_tag', 'with_tag'), ('autohint', 'autohint')], default='default', max_length=100),
        ),
    ]
