# Generated by Django 3.1.6 on 2023-01-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0071_auto_20220827_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
