# Generated by Django 3.1.6 on 2023-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0072_auto_20230106_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='outside_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
