# Generated by Django 3.1.6 on 2023-04-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_game_outside_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referents', to='games.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ticket_price',
            field=models.IntegerField(default=1000),
        ),
    ]
