# Generated by Django 3.1.6 on 2023-04-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0074_auto_20230427_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='with_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_with_referent', to='games.team'),
        ),
    ]
