# Generated by Django 3.1.6 on 2024-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_registration_with_referent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visible_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visible_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
