# Generated by Django 4.2.16 on 2024-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0079_alter_hint_id_alter_hintattempt_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
