# Generated by Django 4.2.16 on 2024-12-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0080_team_name_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='no_html_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
