# Generated by Django 4.2.16 on 2025-03-18 02:26

from django.db import migrations, models


def update_ticket_prices(apps, schema_editor):
    Team = apps.get_model('games', 'Team')
    Team.objects.update(ticket_price=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0081_game_no_html_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ticket_price',
            field=models.IntegerField(default=2000),
        ),
        migrations.RunPython(update_ticket_prices)
    ]
