# Generated by Django 4.2.16 on 2025-03-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0082_alter_team_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name_hash',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
