# Generated by Django 4.2.16 on 2025-03-18 02:38

from django.db import migrations, models

def update_teams(apps, schema_editor):
    Team = apps.get_model('games', 'Team')
    for team in Team.objects.all():
        if not team.name_hash:
            team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0083_alter_team_name_hash'),
    ]

    operations = [
        migrations.RunPython(update_teams)
    ]
