# Generated by Django 4.2.16 on 2026-03-06 19:17

from django.db import migrations


def create_default_projects(apps, schema_editor):
    Project = apps.get_model('games', 'Project')
    for project_id in ('main', 'glowbyte', 'tinkoff', 'lksh', 'tennet', 'tinkoffgeneration', 'umind'):
        Project.objects.get_or_create(id=project_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0085_alter_team_name_hash'),
    ]

    operations = [
        migrations.RunPython(create_default_projects, noop),
    ]
