# Generated by Django 4.2.16 on 2026-03-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0101_ensure_task_types_and_checker_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('default', 'default'), ('wall', 'wall'), ('text_with_forms', 'text_with_forms'), ('replacements_lines', 'replacements_lines'), ('distribute_to_teams', 'distribute_to_teams'), ('with_tag', 'with_tag'), ('autohint', 'autohint')], default='default', max_length=100),
        ),
    ]
