# Generated by Django 4.2.16 on 2026-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0103_game_results_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresultssnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
