# Generated by Django 4.2.16 on 2026-03-25 17:24
#
# MySQL: use online DDL (INPLACE, LOCK=NONE) so EB deploy does not block on long
# table locks while building indexes on large games_attempt / games_hintattempt tables.

from django.db import migrations, models


def _add_indexes_forwards(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'mysql':
        stmts = [
            (
                'CREATE INDEX games_attem_task_id_c73fd5_idx ON games_attempt '
                '(task_id, team_id, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_attem_task_id_198c5d_idx ON games_attempt '
                '(task_id, user_id, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_attem_task_id_85c642_idx ON games_attempt '
                '(task_id, anon_key, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_attem_task_id_bd72cc_idx ON games_attempt '
                '(task_id, status) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_hinta_hint_id_7a53ab_idx ON games_hintattempt '
                '(hint_id, team_id, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_hinta_hint_id_dfdf44_idx ON games_hintattempt '
                '(hint_id, user_id, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_hinta_hint_id_c56ad5_idx ON games_hintattempt '
                '(hint_id, anon_key, time) ALGORITHM=INPLACE LOCK=NONE'
            ),
            (
                'CREATE INDEX games_hinta_hint_id_a6f474_idx ON games_hintattempt '
                '(hint_id, is_real_request) ALGORITHM=INPLACE LOCK=NONE'
            ),
        ]
        with connection.cursor() as cursor:
            for sql in stmts:
                cursor.execute(sql)
        return

    Attempt = apps.get_model('games', 'Attempt')
    HintAttempt = apps.get_model('games', 'HintAttempt')
    schema_editor.add_index(
        Attempt,
        models.Index(fields=['task', 'team', 'time'], name='games_attem_task_id_c73fd5_idx'),
    )
    schema_editor.add_index(
        Attempt,
        models.Index(fields=['task', 'user', 'time'], name='games_attem_task_id_198c5d_idx'),
    )
    schema_editor.add_index(
        Attempt,
        models.Index(fields=['task', 'anon_key', 'time'], name='games_attem_task_id_85c642_idx'),
    )
    schema_editor.add_index(
        Attempt,
        models.Index(fields=['task', 'status'], name='games_attem_task_id_bd72cc_idx'),
    )
    schema_editor.add_index(
        HintAttempt,
        models.Index(fields=['hint', 'team', 'time'], name='games_hinta_hint_id_7a53ab_idx'),
    )
    schema_editor.add_index(
        HintAttempt,
        models.Index(fields=['hint', 'user', 'time'], name='games_hinta_hint_id_dfdf44_idx'),
    )
    schema_editor.add_index(
        HintAttempt,
        models.Index(fields=['hint', 'anon_key', 'time'], name='games_hinta_hint_id_c56ad5_idx'),
    )
    schema_editor.add_index(
        HintAttempt,
        models.Index(fields=['hint', 'is_real_request'], name='games_hinta_hint_id_a6f474_idx'),
    )


def _add_indexes_backwards(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'mysql':
        with connection.cursor() as cursor:
            for name in [
                'games_attem_task_id_c73fd5_idx',
                'games_attem_task_id_198c5d_idx',
                'games_attem_task_id_85c642_idx',
                'games_attem_task_id_bd72cc_idx',
            ]:
                cursor.execute('DROP INDEX `{}` ON games_attempt'.format(name))
            for name in [
                'games_hinta_hint_id_7a53ab_idx',
                'games_hinta_hint_id_dfdf44_idx',
                'games_hinta_hint_id_c56ad5_idx',
                'games_hinta_hint_id_a6f474_idx',
            ]:
                cursor.execute('DROP INDEX `{}` ON games_hintattempt'.format(name))
        return

    Attempt = apps.get_model('games', 'Attempt')
    HintAttempt = apps.get_model('games', 'HintAttempt')
    schema_editor.remove_index(
        Attempt,
        models.Index(fields=['task', 'team', 'time'], name='games_attem_task_id_c73fd5_idx'),
    )
    schema_editor.remove_index(
        Attempt,
        models.Index(fields=['task', 'user', 'time'], name='games_attem_task_id_198c5d_idx'),
    )
    schema_editor.remove_index(
        Attempt,
        models.Index(fields=['task', 'anon_key', 'time'], name='games_attem_task_id_85c642_idx'),
    )
    schema_editor.remove_index(
        Attempt,
        models.Index(fields=['task', 'status'], name='games_attem_task_id_bd72cc_idx'),
    )
    schema_editor.remove_index(
        HintAttempt,
        models.Index(fields=['hint', 'team', 'time'], name='games_hinta_hint_id_7a53ab_idx'),
    )
    schema_editor.remove_index(
        HintAttempt,
        models.Index(fields=['hint', 'user', 'time'], name='games_hinta_hint_id_dfdf44_idx'),
    )
    schema_editor.remove_index(
        HintAttempt,
        models.Index(fields=['hint', 'anon_key', 'time'], name='games_hinta_hint_id_c56ad5_idx'),
    )
    schema_editor.remove_index(
        HintAttempt,
        models.Index(fields=['hint', 'is_real_request'], name='games_hinta_hint_id_a6f474_idx'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0108_alter_task_task_type_alter_taskgroup_view'),
    ]

    operations = [
        # database_operations=[] → migrate finishes instantly; indexes are created
        # in the background by .platform/hooks/postdeploy/02_background_migrations.sh
        # using ALGORITHM=INPLACE LOCK=NONE so live traffic is never blocked.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='attempt',
                    index=models.Index(fields=['task', 'team', 'time'], name='games_attem_task_id_c73fd5_idx'),
                ),
                migrations.AddIndex(
                    model_name='attempt',
                    index=models.Index(fields=['task', 'user', 'time'], name='games_attem_task_id_198c5d_idx'),
                ),
                migrations.AddIndex(
                    model_name='attempt',
                    index=models.Index(fields=['task', 'anon_key', 'time'], name='games_attem_task_id_85c642_idx'),
                ),
                migrations.AddIndex(
                    model_name='attempt',
                    index=models.Index(fields=['task', 'status'], name='games_attem_task_id_bd72cc_idx'),
                ),
                migrations.AddIndex(
                    model_name='hintattempt',
                    index=models.Index(fields=['hint', 'team', 'time'], name='games_hinta_hint_id_7a53ab_idx'),
                ),
                migrations.AddIndex(
                    model_name='hintattempt',
                    index=models.Index(fields=['hint', 'user', 'time'], name='games_hinta_hint_id_dfdf44_idx'),
                ),
                migrations.AddIndex(
                    model_name='hintattempt',
                    index=models.Index(fields=['hint', 'anon_key', 'time'], name='games_hinta_hint_id_c56ad5_idx'),
                ),
                migrations.AddIndex(
                    model_name='hintattempt',
                    index=models.Index(fields=['hint', 'is_real_request'], name='games_hinta_hint_id_a6f474_idx'),
                ),
            ],
            database_operations=[],
        ),
    ]
