# Generated by Django 4.2.16 on 2026-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0108_alter_task_task_type_alter_taskgroup_view'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['task', 'team', 'time'], name='games_attem_task_id_c73fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['task', 'user', 'time'], name='games_attem_task_id_198c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['task', 'anon_key', 'time'], name='games_attem_task_id_85c642_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['task', 'status'], name='games_attem_task_id_bd72cc_idx'),
        ),
        migrations.AddIndex(
            model_name='hintattempt',
            index=models.Index(fields=['hint', 'team', 'time'], name='games_hinta_hint_id_7a53ab_idx'),
        ),
        migrations.AddIndex(
            model_name='hintattempt',
            index=models.Index(fields=['hint', 'user', 'time'], name='games_hinta_hint_id_dfdf44_idx'),
        ),
        migrations.AddIndex(
            model_name='hintattempt',
            index=models.Index(fields=['hint', 'anon_key', 'time'], name='games_hinta_hint_id_c56ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='hintattempt',
            index=models.Index(fields=['hint', 'is_real_request'], name='games_hinta_hint_id_a6f474_idx'),
        ),
    ]
