# Generated by Django 4.2.16 on 2026-03-25 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0109_attempt_games_attem_task_id_c73fd5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_key', models.CharField(blank=True, max_length=64, null=True)),
                ('game_mode', models.CharField(max_length=20)),
                ('state', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.attempt')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_task_states', to='games.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_task_states', to='games.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_task_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'task', 'game_mode'], name='games_chain_team_id_ccb126_idx'), models.Index(fields=['user', 'task', 'game_mode'], name='games_chain_user_id_75f48f_idx'), models.Index(fields=['anon_key', 'task', 'game_mode'], name='games_chain_anon_ke_1a8d9a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'task', 'game_mode'), name='unique_chain_state_team'),
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'task', 'game_mode'), name='unique_chain_state_user'),
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_key__isnull', False)), fields=('anon_key', 'task', 'game_mode'), name='unique_chain_state_anon_key'),
        ),
    ]
