# Generated by Django 4.2.16 on 2026-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0113_taskgroup_gametaskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Не удаляет задание из БД; скрывает везде, кроме админки.', verbose_name='Скрыто из игры и результатов'),
        ),
    ]
