# Generated by Django 4.2.16 on 2026-04-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0115_game_section_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='section_default_rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_section_default_rules', to='games.htmlpage'),
        ),
    ]
