# Generated by Django 4.2.16 on 2026-06-21 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0118_gametaskgroup_number_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGameOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('team_size', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_date', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'заявка на корпоративную игру',
                'verbose_name_plural': 'заявки на корпоративные игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='gametaskgroup',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер круга: целое число или число с точкой (например 1 или 1.5).', regex='^\\d+(?:\\.\\d+)?$')]),
        ),
        migrations.AlterField(
            model_name='hiddenanonkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
