# Generated by Django 4.2.16 on 2026-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0121_raddle_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='points_penalty',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True),
        ),
    ]
