# Generated by Django 4.2.16 on 2026-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0128_corporategameorder_single_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporategameorder',
            name='contact_value',
            field=models.CharField(max_length=254, verbose_name='контакт'),
        ),
    ]
