# Generated by Django 4.2.16 on 2026-07-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0134_ladder_tutorial_two_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('text', models.TextField()),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Dismissed', 'Dismissed')], default='Pending', max_length=100)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='games.game')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='games.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='games.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PendingBugReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.bugreport',),
        ),
    ]
