# Generated by Django 4.2.16 on 2026-07-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0139_telegramgameannouncement_kind_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'событие статистики',
                'verbose_name_plural': 'события статистики',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['kind', 'time'], name='games_stat_kind_time_idx')],
            },
        ),
    ]
