# Generated by Django 4.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0140_statisticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramladderchannelpost',
            name='twitter_tweet_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='X tweet id if also posted at 00:15 prepare (immediate; X has no schedule)',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='telegramladderchannelpost',
            name='twitter_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
