# Generated by Django 4.2.16 on 2026-07-28 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0148_ticketrequest_nowpayments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер подсказки: целое число или число с точкой (например 1 или 1.5).', regex='^\\d+(?:\\.\\d+)?$')]),
        ),
        migrations.AlterField(
            model_name='telegramgameannouncement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_rub', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pay_amount', models.CharField(blank=True, default='', max_length=64)),
                ('pay_currency', models.CharField(blank=True, default='', max_length=16)),
                ('nowpayments_id', models.TextField(blank=True, null=True)),
                ('public_token', models.CharField(db_index=True, default=games.models._donation_public_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
