# Generated by Django 4.2.16 on 2026-08-02 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0156_alphabetty_tutorial_common_word_guesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphabettyDictSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=32)),
                ('suggest_count', models.PositiveIntegerField(default=1)),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alphabetty_dict_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предложение в словарь Алфавитки',
                'verbose_name_plural': 'предложения в словарь Алфавитки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingAlphabettyDictSuggestion',
            fields=[
            ],
            options={
                'verbose_name': 'pending: словарь Алфавитки',
                'verbose_name_plural': 'pending: словарь Алфавитки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.alphabettydictsuggestion',),
        ),
    ]
