# Generated by Django 4.2.16 on 2026-08-03 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0158_alphabetty_tutorial_proper_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabettydictsuggestion',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('ApprovedAnswer', 'Approved for answer'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=32),
        ),
        migrations.CreateModel(
            name='AlphabettyPersonalDictWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=64)),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alphabetty_personal_dict_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'личное слово Алфавитки',
                'verbose_name_plural': 'личные слова Алфавитки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'word'], name='ab_personal_dict_user_word_idx'), models.Index(fields=['anon_key', 'word'], name='ab_personal_dict_anon_word_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='alphabettypersonaldictword',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'word'), name='ab_personal_dict_user_word_uniq'),
        ),
        migrations.AddConstraint(
            model_name='alphabettypersonaldictword',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_key__isnull', False)), fields=('anon_key', 'word'), name='ab_personal_dict_anon_word_uniq'),
        ),
    ]
