# Generated by Django 4.2.16 on 2026-08-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0163_ladder_tutorial_middle_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_handle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='LadderOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлена'), ('accepted', 'Принята')], db_index=True, default='draft', max_length=16)),
                ('share_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('intro', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий для Андрея')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='заметка Андрея при возврате на доработку')),
                ('mixed_script', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_from_offers', to='games.gametaskgroup')),
                ('task_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_offer', to='games.taskgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предложение лесенки',
                'verbose_name_plural': 'предложения лесенок',
                'ordering': ['-updated_at'],
            },
        ),
    ]
