# Generated by Django 4.2.16 on 2026-08-20 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0179_accountmerge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TributePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('expected_product_id', models.BigIntegerField(db_index=True)),
                ('expected_amount', models.BigIntegerField(help_text='Smallest currency units')),
                ('expected_currency', models.CharField(max_length=3)),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular'), ('discount', 'School / student')], max_length=16)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='awaiting_payment', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribute_payment_intents', to='games.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('AMD', 'AMD'), ('EUR', 'EUR')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='payment_provider',
            field=models.CharField(choices=[('manual', 'Manual / legacy'), ('yookassa', 'YooKassa'), ('nowpayments', 'NOWPayments'), ('tribute', 'Tribute (legacy)'), ('tribute_digital', 'Tribute Digital Product'), ('vpos', 'Armenian acquiring / VPOS')], default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='TributePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('product_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.BigIntegerField(blank=True, help_text='Smallest currency units', null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('trb_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_created_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('manual_review', 'Manual review'), ('issued', 'Ticket issued'), ('refunded', 'Refunded')], db_index=True, default='manual_review', max_length=24)),
                ('review_reason', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_review_required', models.BooleanField(db_index=True, default=False)),
                ('matched_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribute_purchases', to='games.team')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribute_purchases', to=settings.AUTH_USER_MODEL)),
                ('payment_intent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='games.tributepaymentintent')),
                ('ticket_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribute_purchase', to='games.ticketrequest')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='tributepaymentintent',
            name='ticket_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tribute_payment_intent', to='games.ticketrequest'),
        ),
        migrations.AddField(
            model_name='tributepaymentintent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribute_payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tributepaymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'awaiting_payment')), fields=('telegram_user_id', 'expected_product_id'), name='uniq_active_tribute_intent_identity_product'),
        ),
    ]
