# Generated by Django 4.2.16 on 2026-08-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0185_word_salad_tutorial_theme_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Fixed', 'Fixed'), ('Dismissed', 'Dismissed')], default='Pending', max_length=100),
        ),
    ]
