# Generated by Django 4.2.16 on 2026-08-27 04:11

from django.db import migrations, models
from django.db.models import F, Q
from django.utils import timezone


def initialise_existing_snapshots(apps, schema_editor):
    DailyGameDifficulty = apps.get_model('games', 'DailyGameDifficulty')
    DailyGameDifficulty.objects.filter(dirty=False, calculated_at__isnull=False).update(
        data_revision=1,
        calculated_revision=1,
        refresh_not_before=F('calculated_at'),
    )
    now = timezone.now()
    DailyGameDifficulty.objects.filter(Q(dirty=True) | Q(calculated_at__isnull=True)).update(
        data_revision=1,
        calculated_revision=0,
        dirty=True,
        refresh_not_before=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0190_telegramdailyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDifficultyNorm',
            fields=[
                ('game_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('typical_time', models.FloatField(blank=True, null=True)),
                ('typical_errors', models.FloatField(blank=True, null=True)),
                ('typical_help_rate', models.FloatField(blank=True, null=True)),
                ('typical_unfinished_rate', models.FloatField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'историческая норма сложности',
                'verbose_name_plural': 'исторические нормы сложности',
            },
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='calculated_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='data_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='norm_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='refresh_claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='refresh_claimed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='refresh_fail_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='refresh_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailygamedifficulty',
            name='refresh_not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dailygamedifficulty',
            index=models.Index(fields=['dirty', 'refresh_not_before'], name='games_dgd_due_idx'),
        ),
        migrations.RunPython(initialise_existing_snapshots, migrations.RunPython.noop),
    ]
