# Generated by Django 4.2.16 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0192_socialqueuepost_telegram_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDifficultyQueueStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_refreshed_count', models.PositiveIntegerField(default=0)),
                ('last_limit', models.PositiveIntegerField(default=0)),
                ('last_worker', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'состояние очереди сложности',
                'verbose_name_plural': 'состояние очереди сложности',
            },
        ),
    ]
