# Generated by Django 4.2.16 on 2026-09-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0195_product_analytics_instrumentation_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySolveTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('timing_version', models.PositiveSmallIntegerField(default=1)),
                ('accumulated_ms', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('auto_paused', 'Auto-paused'), ('manually_paused', 'Manually paused'), ('completed', 'Completed')], db_index=True, default='auto_paused', max_length=32)),
                ('active_session_id', models.UUIDField(blank=True, null=True)),
                ('interval_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('last_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('applied_event_ids', models.JSONField(blank=True, default=list)),
                ('frozen_ms', models.BigIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_solve_timings', to='games.game')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_solve_timings', to='games.taskgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_solve_timings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'время прохождения ежедневной игры',
                'verbose_name_plural': 'времена прохождения ежедневных игр',
                'indexes': [models.Index(fields=['game', 'task_group'], name='games_dst_game_tg_idx'), models.Index(fields=['user', 'game'], name='games_dst_user_game_idx'), models.Index(fields=['anon_key', 'game'], name='games_dst_anon_game_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailysolvetiming',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'game', 'task_group'), name='uniq_daily_timing_user_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='dailysolvetiming',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_key__isnull', False)), fields=('anon_key', 'game', 'task_group'), name='uniq_daily_timing_anon_game_tg'),
        ),
    ]
