# Generated by Django 4.2.16 on 2026-09-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0197_ensure_yandex_social_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSaladOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('idea', 'Идея'), ('full', 'Салатик')], db_index=True, default='full', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлена'), ('accepted', 'Принята')], db_index=True, default='draft', max_length=16)),
                ('share_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('theme', models.TextField(blank=True, default='')),
                ('idea_text', models.TextField(blank=True, default='')),
                ('suggested_words', models.TextField(blank=True, default='')),
                ('grid_text', models.TextField(blank=True, default='')),
                ('words_text', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий для Андрея')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='заметка Андрея при возврате на доработку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_word_salad_offers', to='games.gametaskgroup')),
                ('task_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_salad_offer', to='games.taskgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_salad_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предложение салатика',
                'verbose_name_plural': 'предложения салатиков',
                'ordering': ['-updated_at'],
            },
        ),
    ]
