# Generated by Django 4.2.16 on 2026-09-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0198_word_salad_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlinktoken',
            name='next_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ClubSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tribute', 'Tribute')], db_index=True, default='tribute', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past due')], db_index=True, default='expired', max_length=24)),
                ('tribute_subscription_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tribute_period_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('amount', models.BigIntegerField(blank=True, help_text='Smallest currency units', null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_event', models.CharField(blank=True, default='', max_length=64)),
                ('last_event_created_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_detected', models.BooleanField(db_index=True, default=False)),
                ('payment_success_goal_queued_at', models.DateTimeField(blank=True, null=True)),
                ('payment_success_goal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_goal_queued_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_goal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_goal_queued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_goal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='club_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('tribute_subscription_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tribute_period_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('result', models.CharField(choices=[('applied', 'Applied'), ('duplicate', 'Duplicate'), ('ignored_unknown_product', 'Unknown product'), ('unmatched_telegram', 'Unknown Telegram'), ('malformed', 'Malformed'), ('ignored_type', 'Ignored type'), ('delayed', 'Delayed'), ('anomaly', 'Anomaly')], db_index=True, max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload_excerpt', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('club_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='games.clubsubscription')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
