# Generated by Django 4.2.16 on 2026-09-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0200_word_salad_offer_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextGameVoteGoalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(choices=[('redactle', 'Redactle'), ('cryptic', 'Криптик'), ('logic', 'Логические пазлы')], max_length=32, unique=True)),
                ('donation_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('web_url', models.URLField(blank=True, default='', max_length=500)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'голос: цель Tribute',
                'verbose_name_plural': 'голос: цели Tribute',
                'ordering': ['candidate'],
            },
        ),
        migrations.CreateModel(
            name='NextGameVoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('donation_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tribute_donation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('candidate', models.CharField(blank=True, choices=[('redactle', 'Redactle'), ('cryptic', 'Криптик'), ('logic', 'Логические пазлы')], db_index=True, default='', max_length=32)),
                ('original_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('original_currency', models.CharField(blank=True, default='', max_length=3)),
                ('fx_rate_to_eur', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('normalized_amount_eur_cents', models.BigIntegerField(default=0)),
                ('donation_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(blank=True, default='', max_length=32)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('trb_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('result', models.CharField(choices=[('counted', 'Учтён'), ('duplicate', 'Повтор'), ('unmapped', 'Без кандидата'), ('outside_period', 'Вне периода'), ('ignored_event', 'Игнорирован'), ('unknown_currency', 'Неизвестная валюта'), ('malformed', 'Некорректный payload')], db_index=True, max_length=32)),
                ('include_in_scoreboard', models.BooleanField(db_index=True, default=False)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('excluded_reason', models.TextField(blank=True, default='')),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('payload_excerpt', models.JSONField(blank=True, default=dict)),
                ('analytics_goal_queued_at', models.DateTimeField(blank=True, null=True)),
                ('analytics_goal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_game_vote_exclusions', to=settings.AUTH_USER_MODEL)),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_game_vote_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'голос: Tribute webhook',
                'verbose_name_plural': 'голос: Tribute webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='NextGameVoteCampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('freeze_reason', models.CharField(blank=True, choices=[('deadline', 'Дедлайн'), ('manual', 'Вручную')], default='', max_length=16)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('winner_slug', models.CharField(blank=True, default='', max_length=32)),
                ('is_tie', models.BooleanField(default=False)),
                ('mapping_blocker', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_game_vote_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'голос: состояние кампании',
                'verbose_name_plural': 'голос: состояние кампании',
            },
        ),
        migrations.CreateModel(
            name='NextGameVoteAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(choices=[('redactle', 'Redactle'), ('cryptic', 'Криптик'), ('logic', 'Логические пазлы')], db_index=True, max_length=32)),
                ('amount_eur_cents', models.BigIntegerField(help_text='Корректировка в евроцентах; может быть отрицательной')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_game_vote_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'голос: ручная корректировка',
                'verbose_name_plural': 'голос: ручные корректировки',
                'ordering': ['-created_at'],
            },
        ),
    ]
