# Generated by Django 4.2.16 on 2026-09-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0207_word_salad_offer_converted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='intro_offer_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='next_charge_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='payment_method_save_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='plan',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('monthly', 'Monthly'), ('annual', 'Annual')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='clubsubscription',
            name='yookassa_payment_method_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='clubsubscription',
            name='provider',
            field=models.CharField(choices=[('tribute', 'Tribute'), ('yookassa', 'YooKassa')], db_index=True, default='tribute', max_length=16),
        ),
        migrations.AlterField(
            model_name='clubsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past due')], db_index=True, default='expired', max_length=24),
        ),
        migrations.CreateModel(
            name='ClubYooKassaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('kind', models.CharField(choices=[('initial_monthly', 'Initial monthly'), ('recurring_monthly', 'Recurring monthly'), ('annual', 'Annual')], db_index=True, max_length=32)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('period_key', models.CharField(help_text='Stable billing-period key for uniqueness, e.g. 2026-10-15:recurring_monthly', max_length=64)),
                ('amount', models.PositiveIntegerField(help_text='Kopecks')),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('confirmation_url', models.URLField(blank=True, default='', max_length=500)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('club_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yookassa_payments', to='games.clubsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_yookassa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clubyookassapayment',
            constraint=models.UniqueConstraint(condition=models.Q(('yookassa_payment_id', ''), _negated=True), fields=('yookassa_payment_id',), name='club_yk_payment_yookassa_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='clubyookassapayment',
            constraint=models.UniqueConstraint(fields=('club_subscription', 'period_key'), name='club_yk_payment_period_key_uniq'),
        ),
    ]
