# Generated by Django 4.2.16 on 2026-09-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0210_daily_games_are_not_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplaySlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('actor_key', models.CharField(editable=False, max_length=128)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_slots', to='games.game')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_slots', to='games.taskgroup')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_slots', to='games.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['game', 'task_group', 'updated_at'], name='games_replay_slot_game_tg_idx'),
                    models.Index(fields=['run_id'], name='games_replay_slot_run_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='attempt', name='replay_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.replayslot'),
        ),
        migrations.AddField(
            model_name='chaintaskstate', name='replay_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_task_states', to='games.replayslot'),
        ),
        migrations.AddField(
            model_name='dailysolvetiming', name='replay_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_timings', to='games.replayslot'),
        ),
        migrations.AddField(
            model_name='hintattempt', name='replay_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hint_attempts', to='games.replayslot'),
        ),
        migrations.RemoveConstraint(model_name='chaintaskstate', name='unique_chain_state_team_game'),
        migrations.RemoveConstraint(model_name='chaintaskstate', name='unique_chain_state_user_game'),
        migrations.RemoveConstraint(model_name='chaintaskstate', name='unique_chain_state_anon_key_game'),
        migrations.RemoveConstraint(model_name='dailysolvetiming', name='uniq_daily_timing_user_game_tg'),
        migrations.RemoveConstraint(model_name='dailysolvetiming', name='uniq_daily_timing_anon_game_tg'),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['replay_slot', 'task', 'game', 'time'], name='games_att_rep_task_time_idx'),
        ),
        migrations.AddIndex(
            model_name='chaintaskstate',
            index=models.Index(fields=['replay_slot', 'task', 'game', 'game_mode'], name='games_chain_replay__d7106a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysolvetiming',
            index=models.Index(fields=['replay_slot', 'game', 'task_group'], name='games_dst_replay_game_tg_idx'),
        ),
        migrations.AddIndex(
            model_name='hintattempt',
            index=models.Index(fields=['replay_slot', 'hint', 'time'], name='games_hinta_replay__22914c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(team__isnull=False), fields=('team', 'task', 'game', 'game_mode', 'replay_slot'), name='unique_chain_state_team_game'),
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('user', 'task', 'game', 'game_mode', 'replay_slot'), name='unique_chain_state_user_game'),
        ),
        migrations.AddConstraint(
            model_name='chaintaskstate',
            constraint=models.UniqueConstraint(condition=models.Q(anon_key__isnull=False), fields=('anon_key', 'task', 'game', 'game_mode', 'replay_slot'), name='unique_chain_state_anon_key_game'),
        ),
        migrations.AddConstraint(
            model_name='dailysolvetiming',
            constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('user', 'game', 'task_group', 'replay_slot'), name='uniq_daily_timing_user_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='dailysolvetiming',
            constraint=models.UniqueConstraint(condition=models.Q(anon_key__isnull=False), fields=('anon_key', 'game', 'task_group', 'replay_slot'), name='uniq_daily_timing_anon_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='replayslot',
            constraint=models.UniqueConstraint(fields=('actor_key', 'game', 'task_group'), name='uniq_replay_slot_actor_key_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='replayslot',
            constraint=models.UniqueConstraint(condition=models.Q(team__isnull=False), fields=('team', 'game', 'task_group'), name='uniq_replay_slot_team_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='replayslot',
            constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('user', 'game', 'task_group'), name='uniq_replay_slot_user_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='replayslot',
            constraint=models.UniqueConstraint(condition=models.Q(anon_key__isnull=False), fields=('anon_key', 'game', 'task_group'), name='uniq_replay_slot_anon_game_tg'),
        ),
        migrations.AddConstraint(
            model_name='replayslot',
            constraint=models.CheckConstraint(
                check=(
                    (models.Q(team__isnull=False) & models.Q(user__isnull=True) & models.Q(anon_key__isnull=True))
                    | (models.Q(team__isnull=True) & models.Q(user__isnull=False) & models.Q(anon_key__isnull=True))
                    | (models.Q(team__isnull=True) & models.Q(user__isnull=True) & models.Q(anon_key__isnull=False))
                ),
                name='replay_slot_exactly_one_actor',
            ),
        ),
    ]
