# Generated by Django 4.2.16 on 2026-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0211_replayslot_and_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Не удаляет результаты; скрывает профиль из публичных таблиц.', verbose_name='Скрыт из публичных результатов'),
        ),
    ]
