# Generated by Django 4.2.16 on 2026-09-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0212_profile_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Зарегистрированные авторы для исключения из таблицы результатов этого выпуска.', related_name='authored_task_groups', to='games.profile', verbose_name='Авторы задания'),
        ),
    ]
