# Generated by Django 4.2.16 on 2026-09-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0214_daily_result_projection'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyresultprojection',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('actor_type', 'team'), ('anon_key__isnull', True), ('team__isnull', False), ('user__isnull', True)),
                    models.Q(('actor_type', 'user'), ('anon_key__isnull', True), ('team__isnull', True), ('user__isnull', False)),
                    models.Q(('actor_type', 'anon'), ('anon_key__isnull', False), ('team__isnull', True), ('user__isnull', True)),
                    _connector='OR',
                ),
                name='daily_proj_actor_shape',
            ),
        ),
        migrations.CreateModel(
            name='DailyResultProjectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('source_revision', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_result_projection_states', to='games.game')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_result_projection_states', to='games.taskgroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyresultprojectionstate',
            constraint=models.UniqueConstraint(fields=('game', 'task_group'), name='uniq_daily_proj_state_release'),
        ),
    ]
