# Generated by Django 4.2.16 on 2026-09-27 12:04

from django.db import migrations, models
import games.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0231_gametaskgroup_share_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialqueuepost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=games.storage_backends.social_queue_storage, upload_to='social_queue/'),
        ),
        migrations.AlterField(
            model_name='socialqueuepost',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Optional compact image for X, Instagram and Threads; Telegram uses image.', null=True, storage=games.storage_backends.social_queue_storage, upload_to='social_queue/'),
        ),
    ]
