# Generated by Django 4.2.16 on 2026-09-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0232_socialqueuepost_s3_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsaladrecheckjob',
            name='pending_resolution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
