# Generated by Django 4.2.16 on 2026-09-28 10:53

from django.db import migrations, models


def add_status_index_if_missing(apps, schema_editor):
    Attempt = apps.get_model('games', 'Attempt')
    index_name = 'games_attempt_status_idx'
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor,
            Attempt._meta.db_table,
        )
    if index_name not in constraints:
        schema_editor.add_index(
            Attempt,
            models.Index(fields=['status'], name=index_name),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0234_chaintaskstate_actor_key'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_status_index_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='attempt',
                    index=models.Index(fields=['status'], name='games_attempt_status_idx'),
                ),
            ],
        ),
    ]
