# Generated by Django 4.2.16 on 2026-09-30 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0242_account_merge_job_next_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_telegram_user_id', models.BigIntegerField(db_index=True)),
                ('recipient_telegram_username', models.CharField(blank=True, default='', max_length=64)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_forever', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('claimed', 'Claimed'), ('revoked', 'Revoked')], db_index=True, default='created', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_subscription_gifts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_subscription_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paid', 'Paid'), ('gift', 'Gift'), ('manual', 'Manual')], db_index=True, max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('club_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='games.clubsubscription')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_club_entitlements', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='games.subscriptiongift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptiongift',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('duration_months__isnull', True), ('is_forever', True)), models.Q(('duration_months__isnull', False), ('is_forever', False)), _connector='OR'), name='subscription_gift_duration_valid'),
        ),
        migrations.AddConstraint(
            model_name='clubentitlement',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='club_entitlement_period_valid'),
        ),
    ]
