# Generated by Django 4.2.16 on 2026-09-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0243_subscriptiongift_clubentitlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubentitlement',
            name='tribute_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='games.clubsubscriptionevent'),
        ),
        migrations.AddField(
            model_name='clubentitlement',
            name='yookassa_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='games.clubyookassapayment'),
        ),
    ]
