# Generated by Django 4.2.16 on 2026-09-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0244_clubentitlement_tribute_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiongift',
            name='created_by_telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
