# Generated by Django 4.2.16 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0245_subscriptiongift_created_by_telegram_user_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('yookassa_payment__isnull', False)), fields=('yookassa_payment',), name='club_entitlement_yookassa_payment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='clubentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('tribute_event__isnull', False)), fields=('tribute_event',), name='club_entitlement_tribute_event_uniq'),
        ),
    ]
