# Generated by Django 4.2.16 on 2026-10-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0254_dailysolvetimingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('session_id', models.CharField(max_length=128)),
                ('event_id', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('start', 'Start'), ('resume', 'Resume'), ('heartbeat', 'Heartbeat'), ('auto_pause', 'Auto-pause'), ('pause', 'Pause'), ('complete', 'Complete')], max_length=16)),
                ('seq', models.BigIntegerField(default=0)),
                ('claimed_ms', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_timing_events', to='games.game')),
                ('replay_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_timing_events', to='games.replayslot')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_timing_events', to='games.taskgroup')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_timing_events', to='games.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_timing_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'task_group', 'session_id', 'seq'], name='games_dte_session_seq_idx'), models.Index(fields=['game', 'task_group', 'occurred_at'], name='games_dte_release_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailytimingevent',
            constraint=models.UniqueConstraint(fields=('game', 'task_group', 'session_id', 'event_id'), name='uniq_daily_timing_event_id'),
        ),
        migrations.AddConstraint(
            model_name='dailytimingevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anon_key__isnull', True), ('team__isnull', True), ('user__isnull', False)), models.Q(('anon_key__isnull', True), ('team__isnull', False), ('user__isnull', True)), models.Q(('anon_key__isnull', False), ('team__isnull', True), ('user__isnull', True)), _connector='OR'), name='daily_timing_event_actor_shape'),
        ),
    ]
