# Generated by Django 4.2.16 on 2026-10-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0255_daily_timing_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimingevent',
            name='client_occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
