# Generated by Django 4.2.16 on 2026-10-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0256_daily_timing_event_client_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiongift',
            name='code_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptiongift',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongift',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongift',
            name='provider',
            field=models.CharField(blank=True, choices=[('yookassa', 'YooKassa'), ('tribute', 'Tribute')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='subscriptiongift',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_subscription_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptiongift',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='created', max_length=16),
        ),
        migrations.CreateModel(
            name='SubscriptionGiftPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'YooKassa'), ('tribute', 'Tribute')], max_length=16)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('expected_amount', models.PositiveIntegerField(help_text='Smallest currency units')),
                ('currency', models.CharField(max_length=3)),
                ('duration_months', models.PositiveIntegerField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=16)),
                ('confirmation_url', models.URLField(blank=True, default='', max_length=500)),
                ('purchase_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('raw_event_excerpt', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='games.subscriptiongift')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_gift_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptiongiftpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='subscription_gift_payment_provider_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongiftpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_id', ''), _negated=True), fields=('provider', 'purchase_id'), name='subscription_gift_payment_purchase_id_uniq'),
        ),
    ]
