# Generated by Django 4.2.16 on 2026-10-01 11:48

from django.db import migrations, models


def populate_actor_keys(apps, schema_editor):
    Event = apps.get_model('games', 'DailyTimingEvent')
    for event in Event.objects.all().iterator(chunk_size=500):
        if event.team_id:
            key = 'team:{}'.format(event.team_id)
        elif event.user_id:
            key = 'user:{}'.format(event.user_id)
        elif event.anon_key:
            key = 'anon:{}'.format(event.anon_key)
        else:
            key = 'unknown'
        if event.replay_slot_id:
            key += ':replay:{}'.format(event.replay_slot_id)
        event.actor_key = key[:160]
        event.save(update_fields=['actor_key'])


def clear_actor_keys(apps, schema_editor):
    Event = apps.get_model('games', 'DailyTimingEvent')
    Event.objects.update(actor_key='')


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0257_subscriptiongift_code_ciphertext_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailytimingevent',
            name='uniq_daily_timing_event_id',
        ),
        migrations.AddField(
            model_name='dailytimingevent',
            name='actor_key',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.RunPython(populate_actor_keys, clear_actor_keys),
        migrations.AddConstraint(
            model_name='dailytimingevent',
            constraint=models.UniqueConstraint(fields=('game', 'task_group', 'actor_key', 'session_id', 'event_id'), name='uniq_daily_timing_event_id'),
        ),
    ]
