# Generated by Django 4.2.16 on 2026-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0258_daily_timing_event_actor_key'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailytimingevent',
            index=models.Index(fields=['game', 'task_group', 'actor_key', 'session_id', 'occurred_at'], name='games_dte_audit_order_idx'),
        ),
    ]
